### ISSUE TITLE
Generated .gif is huge

### ISSUE THREAD

**Issue by Silex** [Malabarba/camcorder.el#3]
Do you know about this issue?

See https://github.com/Silex/ido-vertical-mode.el/blob/master/screenshot-static.gif (https://github.com/Silex/ido-vertical-mode.el#static--fixed)

Maybe it's all normal but it looks weird to have 7Mb for such a short & simple gif.

**Comment by Malabarba** [comment]
Yes, this (among other things) is a flaw of recordmydesktop. Unfortunately I couldn't find any other utility that allowed gif recording without predetermined timeout. =/

If anybody knows one, I'm all ears.

**Comment by Silex** [comment]
Given the simplicity of gif's format, I'm pretty sure we can reduce its size easily?

I'm away this week-end but a quick google told me `convert test.gif -fuzz 20% -layers Optimize result.gif`, the end result is fugly but the gif is 200K now :)

I'll try to find something better when I come back, I'm pretty sure we can simply remove all the identical frames and pause them longer instead.

**Comment by Malabarba** [comment]
I'm a little wary of making the end result even fuglier than it already is. =/
The gifs are already much lower quality than those generated by bluzanz, for instance.

**Comment by Malabarba** [comment]
The annoying part is that the `ogv` generated by `recordmydesktop` is actually very nice (good quality and light weight), it's our conversion process that just wrecks it. But I couln't find a good way to convert it to a gif.

**Comment by Silex** [comment]
Ideas: http://askubuntu.com/questions/107726/how-to-create-animated-gif-images-of-a-screencast

**Comment by Malabarba** [comment]
Thanks for the link.
That's almost what we do already, except we use png instead of jpeg in the mplayer step.
I imagine that would lead to a good improvement but it might increase the conversion time by a lot, let me know if you do any tests.

I tried the second suggestion there (doing convert with fuzzy), but that completely hung my laptop on a 40mb gif, so I'm wary about including it.

One thing I've been considering is to just save the generated `.ogv` file at first (which is very light and very good quality), and then just offer some additional commands to convert it to gif in various ways.

**Comment by Silex** [comment]
> One thing I've been considering is to just save the generated .ogv file at first (which is very light and very good quality), and then just offer some additional commands to convert it to gif in various ways.

Yeah, you'd definitly do that. Keeping the raw original material is always a good idea.

**Comment by Malabarba** [comment]
The latest two commits should address this. The default behavior is now to save the ogv file. Then, there is a `-conver-to-gif` command which you can invoke and it will offer yo several different convertion possibilities.

**Comment by Silex** [comment]
:+1:
